[package]
name = "space-shooter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
matchbox_socket = "0.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = "0.3"
